### ISSUE TITLE
Panic on `attempt to subtract with overflow`

### ISSUE THREAD

**Issue by daniellockyer** [rusticata/radius-parser#1]
Using `cargo-fuzz`, I found the following bug:

```
'attempt to subtract with overflow', src/radius_attr.rs:43:28
```

The line in question subtracts 2 from `l` but this can be < 2.

I would submit a patch wrapping the line with `cond!` but the program interface may have to change. As a result, I'll leave it to the developer.

**Comment by chifflier** [comment]
Good catch, thanks.
I used `verify!` to avoid changing the API, and raise a parse error if length is `< 2`.
