### ISSUE TITLE
Choose a more permissive license (e.g. MIT, Apache)

### ISSUE THREAD

**Issue by vorot93** [rusticata/radius-parser#3]
Dynamic linking is not really a canonical way of doing things in the Rust world (as opposed to C/C++ one). Therefore [using this library forces you into LGPL 2.1 as well](https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic). That's why most Rust libraries out there are distributed under MIT, Apache or both. Perhaps relicense this library as well and open it up to the community at large?

**Comment by chifflier** [comment]
Hum, the static vs dynamic difference is indeed a problem. I'll change the license (probably to be dual license), I just have to think about it before, since I'll change it for all my crates
